[package]
name = "great_kingdom_core"
version.workspace = true
edition.workspace = true

[lib]
name = "great_kingdom_core"
crate-type = ["cdylib", "rlib"]

[features]
default = []
extension-module = ["pyo3/extension-module"]
onnx-cuda = [
    "great_kingdom_onnx/cuda",
    "great_kingdom_gumbel/cuda",
    "great_kingdom_klent/cuda",
]

[dependencies]
great_kingdom_engine = { path = "../crates/great_kingdom_engine" }
great_kingdom_features = { path = "../crates/great_kingdom_features" }
great_kingdom_gumbel = { path = "../crates/great_kingdom_gumbel" }
great_kingdom_klent = { path = "../crates/great_kingdom_klent" }
great_kingdom_onnx = { path = "../crates/great_kingdom_onnx" }
pyo3.workspace = true
rayon.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
